### ISSUE TITLE
События отправки

### ISSUE THREAD

**Issue by kernusr** [wedal/mod_wedal_joomla_callback#1]
Я что-то не понял, а как то можно повязаться на событие отправки формы?
Например, я хочу цели ловить на отправке?
Посмотрел в js - там нет генерации собственных событий, чтобы можно было на них подписаться
Посмотрел в PHP - там js подключается "напрямую" из модуля, без возможности переопределения

**Comment by wedal** [comment]
Да, пока всё так, к сожалению. Старый модуль, старый подход. 

Сейчас, из-за этого переписываю его полностью для поддержки J4 и доп.полей, а также переопределений JS и событий. 

Пока могу предложить только хакнуть или форкнуть. Очень мала вероятность, что текущая версия будет обновляться. А новая будет уже сильно изменена и включит все, описанное выше.
